# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  smtp_address:              TODO
  smtp_port:                 TODO
  smtp_domain:               TODO
  smtp_user_name:            TODO
  smtp_password:             TODO
  smtp_authentication:       TODO
  smtp_enable_starttls_auto: TODO
  smtp_ssl:                  TODO

development:
  <<: *default
  secret_key_base:   TODO # Use `$ rails secret`
  database_username: TODO
  database_password: TODO
  default_url_host:  TODO # E.g. localhost:3001 (be sure to use the same port that's used by puma, see puma.rb)

test:
  <<: *default
  secret_key_base:   TODO # Use `$ rails secret`
  database_username: TODO
  database_password: TODO
  default_url_host:  TODO # You should use the same like for development to make Capybara.asset_host work!

# This is only needed on the production server!
production:
  <<: *default
  secret_key_base:   TODO # Use `$ rails secret`
  database:          TODO
  database_username: TODO
  database_password: TODO
  default_url_host:  TODO # E.g. base.sirius.uberspace.de